### PR TITLE
Fix block size evaluation (#1212)

### PR DESCRIPTION
**Pull request by uweseimet**
```
>piscsi -F /home/pi/images -ID0 -b 1024 test.hds
>scsictl -s
...
 0:0  SCHD  PiSCSI:SCSI HD 15 MiB:2305  1024 bytes per sector  15728640 bytes capacity  /home/us/hatari/test.hds  read-only
```

### CODE REVIEW

**Comment by uweseimet** [comment]
@akuker The SonarCloud job for this PR reports
```
2023-09-15T09:36:38.9794359Z ERROR: Error during SonarScanner execution
2023-09-15T09:36:38.9795725Z ERROR: Something went wrong while trying to get the pullrequest with key '1213'
2023-09-15T09:36:38.9797098Z ERROR: Caused by: Error 500 on https://sonarcloud.io/api/alm_integration/show_pullrequest?project=akuker_PISCSI&pullrequestKey=1213 : {"errors":[{"msg":"An unexpected error occurred. Please try again later."}]}
```
I re-tried several times without success. The SonarCloud job of the related issue runs fine. Because these two jobs run on the same sources I suspect something is wrong with the PR action. Can you please check?

**Comment by uweseimet** [comment]
I would appreciate a code review and also for a review of the PR issue ...

**Comment by akuker** [comment]
@uweseimet - Sorry I missed the email for this! I'll take a look this evening.

**Comment by uweseimet** [comment]
@akuker It's just a few lines.

Do you intend to release a final release compatible with buster? I am asking because changes are piling up (#1179 and #1182), which I intended to create no PR for until bookworm is available. Not merging these changes has to started to block my work on other tickets, though, so in case there is no plan for another buster release I would like to merge my changes earlier, i.e. before bookworm is available.
In case you are unsure, another buster release could be created from a branch based on the current develop branch any time, even if my changes were merged. So merging my pending changes would not prevent another buster release, but would definitely make my life easier ;-).

**Comment by uweseimet** [comment]
@akuker OK, sounds good. Regarding SonarCloud you changed something related to PR actions some time ago, commit #74eef6f9. This might be related.

**Comment by uweseimet** [comment]
Regarding the next steps (PRs for #1179 and #1182) there are two approaches: Separate PRs for each ticket, or a single PR for #1182 only, because #1182 includes all changes of #1179. #1179 is just an intermediate step.
IMO having a single PR for #1182 requires less review work. Any preference?

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
> IMO having a single PR for #1182 requires less review work than two separate PRs. Any preference?

Agreed. Single PR is good with me.

**Pull request merged**
