### PR TITLE
Web UI: Explicitly strip newlines from chunks when uploading

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark Just a question on this. Please bear with me if this question does not apply for this ticket, because I have not digged deeper into this.
In general, issues caused by newlines are typical for cases where the upload protocol/format is not a binary format. A good example is ftp, where you can choose between text/ASCII and binary transfer format. If you transfer binaries with text format enabled you run into very similar issues with ftp like the one this ticket is addressing. Can it be that there is a general problem with uploading binaries in the web UI, e.g. because the code or the libraries used are trying to deal with text instead of binary format?

**Review by nucleogenic — APPROVED** [review]
Looking at what's been discussed in the ticket, the change seems reasonable enough. It would be better if we could understand why the issue isn't reproducible between users though. There's seemingly a component to this problem we don't understand 🤔

**Comment by uweseimet** [comment]
@nucleogenic I would have appreciated if somebody had explained why my concerns are not justified and a sequence of line feed characters that is actually a valid part of the binary cannot just be stripped.

**Comment by rdmark** [comment]
@uweseimet Yes, It's a mystery where the CRLF comes from. Your theory sounds believable, that somewhere in the software stack the data is treated as text and not binary. 

In the python code we create the file object in binary append mode, as per the documentation: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

The one thing I can imagine is that a corner case bug with dropzone.js and the particular version of Chrome that the reporter is using.

I'm hoping that we can get some more feedback and test data from the user and then decide what to do next.

**Comment by uweseimet** [comment]
@rdmark In order to reproduce this problem, what about creating an image file that only contains sequences of CR, CR/LF and LF and that is big enough to require several chunks? For testing the upload there is no need for an image with valid filesystems.
If there is an issue with binary/ASCII format, it might also depend on the charsets/locales used on the client and the server.

**Comment by rdmark** [comment]
@uweseimet A file consisting of nothing but CRLF does indeed get corrupted with the code in this PR. (And works before the change.)

One idea I had, is to add a check for the size of a transferred chunk, and strip trailing line endings only when the actual size exceeds the expected size. Thoughts?

**Comment by uweseimet** [comment]
IMO this is not a solution. I bet that you are missing something.Am 29.10.2023 09:16 schrieb Daniel Markstedt ***@***.***>:
@uweseimet A file consisting of nothing but CRLF does indeed get corrupted with the code in this PR. (And works before the change.)
One idea I had, is to add a check for the size of a transferred chunk, and strip trailing line endings only when the actual size exceeds the expected size. Thoughts?

**Comment by rdmark** [comment]
I added some debug output and will ask the original reporter to test once they respond. Logging should at least tell us if the chunk size and offsets are correct.

**Comment by uweseimet** [comment]
I recommend not to change anything until it is fully clear where this problem comes from, and there should be more than one user who can reproduce it.All in all either the technologies you are using cannot deal with binary uploads (unlikely), you are not using them correctly and are missing something, or there is no problem and the respective user's setup is some broken.IMO there are no other alternatives.Am 29.10.2023 12:33 schrieb Daniel Markstedt ***@***.***>:
I added some debug output and will ask the original reporter to test once they respond. Logging should at least tell us if the chunk size and offsets are correct.

**Comment by uweseimet** [comment]
@rdmark Correct me if I am wrong: The latest comments in #1157 say that there is no problem at all, don't they?

**Comment by rdmark** [comment]
I want to ask the original reporter to try one more thing: the current develop code... just to make sure that the adding of the logging didn't have an effect on their corner case.

**Pull request closed without merging**
