### PR TITLE
Issue 1179 and 1182

### PR DESCRIPTION
**Pull request by uweseimet**
Besides resolving #1179 and #1182 this PR also resolves several SonarQube issues and idecouples several classes, which also simplifies the unit test setup.

github also lists files as changed that have not been changed at all. This is the correct list:
```
>git diff --name-only develop
cpp/Makefile
cpp/controllers/abstract_controller.cpp
cpp/controllers/abstract_controller.h
cpp/controllers/controller_manager.cpp
cpp/controllers/controller_manager.h
cpp/controllers/phase_handler.h
cpp/controllers/scsi_controller.cpp
cpp/controllers/scsi_controller.h
cpp/devices/cd_track.h
cpp/devices/cfilesystem.cpp
cpp/devices/cfilesystem.h
cpp/devices/ctapdriver.cpp
cpp/devices/ctapdriver.h
cpp/devices/device.cpp
cpp/devices/device.h
cpp/devices/device_factory.cpp
cpp/devices/device_factory.h
cpp/devices/device_logger.cpp
cpp/devices/device_logger.h
cpp/devices/disk.cpp
cpp/devices/disk.h
cpp/devices/disk_cache.cpp
cpp/devices/disk_cache.h
cpp/devices/disk_track.cpp
cpp/devices/disk_track.h
cpp/devices/host_services.cpp
cpp/devices/host_services.h
cpp/devices/interfaces/byte_writer.h
cpp/devices/mode_page_device.cpp
cpp/devices/mode_page_device.h
cpp/devices/primary_device.cpp
cpp/devices/primary_device.h
cpp/devices/scsi_command_util.cpp
cpp/devices/scsi_command_util.h
cpp/devices/scsi_daynaport.cpp
cpp/devices/scsi_daynaport.h
cpp/devices/scsi_host_bridge.cpp
cpp/devices/scsi_host_bridge.h
cpp/devices/scsi_printer.cpp
cpp/devices/scsi_printer.h
cpp/devices/scsicd.cpp
cpp/devices/scsicd.h
cpp/devices/scsihd.cpp
cpp/devices/scsihd.h
cpp/devices/scsihd_nec.cpp
cpp/devices/scsihd_nec.h
cpp/devices/scsimo.cpp
cpp/devices/scsimo.h
cpp/devices/storage_device.cpp
cpp/devices/storage_device.h
cpp/hal/data_sample.h
cpp/hal/gpiobus.cpp
cpp/hal/gpiobus.h
cpp/hal/gpiobus_bananam2p.cpp
cpp/hal/gpiobus_bananam2p.h
cpp/hal/gpiobus_factory.cpp
cpp/hal/gpiobus_raspberry.cpp
cpp/hal/gpiobus_raspberry.h
cpp/hal/gpiobus_virtual.cpp
cpp/hal/gpiobus_virtual.h
cpp/hal/log.h
cpp/hal/sbc_version.cpp
cpp/hal/sbc_version.h
cpp/hal/sunxi_utils.cpp
cpp/hal/systimer.cpp
cpp/hal/systimer_allwinner.cpp
cpp/hal/systimer_raspberry.cpp
cpp/monitor/sm_core.cpp
cpp/monitor/sm_core.h
cpp/monitor/sm_html_report.cpp
cpp/monitor/sm_json_report.cpp
cpp/monitor/sm_vcd_report.cpp
cpp/piscsi.cpp
cpp/piscsi/command_context.cpp
cpp/piscsi/command_context.h
cpp/piscsi/localizer.cpp
cpp/piscsi/localizer.h
cpp/piscsi/piscsi_core.cpp
cpp/piscsi/piscsi_core.h
cpp/piscsi/piscsi_executor.cpp
cpp/piscsi/piscsi_executor.h
cpp/piscsi/piscsi_image.cpp
cpp/piscsi/piscsi_image.h
cpp/piscsi/piscsi_response.cpp
cpp/piscsi/piscsi_response.h
cpp/piscsi/piscsi_service.cpp
cpp/piscsi/piscsi_service.h
cpp/piscsi_interface.proto
cpp/scsictl/scsictl_commands.cpp
cpp/scsictl/scsictl_commands.h
cpp/scsictl/scsictl_core.cpp
cpp/scsictl/scsictl_display.cpp
cpp/scsictl/scsictl_display.h
cpp/scsictl/scsictl_parser.cpp
cpp/scsictl/scsictl_parser.h
cpp/scsidump.cpp
cpp/scsidump/scsidump_core.cpp
cpp/scsidump/scsidump_core.h
cpp/scsiloop/scsiloop_core.cpp
cpp/scsiloop/scsiloop_cout.cpp
cpp/scsiloop/scsiloop_cout.h
cpp/scsiloop/scsiloop_gpio.cpp
cpp/scsiloop/scsiloop_gpio.h
cpp/scsiloop/scsiloop_timer.cpp
cpp/shared/config.h
cpp/shared/network_util.cpp
cpp/shared/network_util.h
cpp/shared/piscsi_exceptions.h
cpp/shared/piscsi_util.cpp
cpp/shared/piscsi_util.h
cpp/shared/piscsi_version.cpp
cpp/shared/protobuf_serializer.cpp
cpp/shared/protobuf_serializer.h
cpp/shared/protobuf_util.cpp
cpp/shared/protobuf_util.h
cpp/shared/scsi.h
cpp/test/abstract_controller_test.cpp
cpp/test/command_context_test.cpp
cpp/test/controller_manager_test.cpp
cpp/test/ctapdriver_test.cpp
cpp/test/device_factory_test.cpp
cpp/test/device_test.cpp
cpp/test/disk_test.cpp
cpp/test/gpiobus_raspberry_test.cpp
cpp/test/host_services_test.cpp
cpp/test/linux_os_stubs.cpp
cpp/test/mocks.h
cpp/test/mode_page_device_test.cpp
cpp/test/network_util_test.cpp
cpp/test/phase_handler_test.cpp
cpp/test/piscsi_exceptions_test.cpp
cpp/test/piscsi_executor_test.cpp
cpp/test/piscsi_image_test.cpp
cpp/test/piscsi_response_test.cpp
cpp/test/piscsi_service_test.cpp
cpp/test/piscsi_util_test.cpp
cpp/test/primary_device_test.cpp
cpp/test/protobuf_serializer_test.cpp
cpp/test/protobuf_util_test.cpp
cpp/test/scsi_command_util_test.cpp
cpp/test/scsi_controller_test.cpp
cpp/test/scsi_daynaport_test.cpp
cpp/test/scsi_host_bridge_test.cpp
cpp/test/scsi_printer_test.cpp
cpp/test/scsicd_test.cpp
cpp/test/scsictl_commands_test.cpp
cpp/test/scsictl_display_test.cpp
cpp/test/scsihd_nec_test.cpp
cpp/test/scsihd_test.cpp
cpp/test/scsimo_test.cpp
cpp/test/storage_device_test.cpp
cpp/test/test_setup.cpp
cpp/test/test_shared.cpp
cpp/test/test_shared.h
doc/piscsi.1
doc/piscsi_man_page.txt
doc/scsictl.1
doc/scsictl_man_page.txt
docker/README.md
docker/docker-compose.yml
docker/web/Dockerfile
easyinstall.sh
```

### CODE REVIEW

**Comment by uweseimet** [comment]
@akuker Looks as if the PR analysis still does not work.

**Comment by uweseimet** [comment]
The branch analysis for the same code worked fine.

**Comment by akuker** [comment]
@uweseimet  - This is trying to merge directly to main. Could you update to merge to develop?

**Comment by akuker** [comment]
> The branch analysis for the same code worked fine.

All of your branches are going to need the project key change merged to work.

**Comment by uweseimet** [comment]
@akuker Oops, I forgot to set develop as the reference branch. I will close this PR and create a new one.

**Pull request closed without merging**
