### PR TITLE
Move top-level .cpp files into their respective folders

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by uweseimet** [comment]
@dialtr I still cannot add you to the reviewers list. This is probably because you are not in the list of collaborators.

@akuker @rdmark Can you please add Tom to this list? I addition, I would appreciate the change of the SonarCloud setting I asked for in https://github.com/PiSCSI/piscsi/pull/1232 to be applied:

Please disable this warning in SonarCloud:
```
Reduce verbosity with "using enum"
```
We cannot address this issue because the bullseye compiler does not support "using enum", and whether/where to use "using enum" is optional anyway.

**Comment by akuker** [comment]
> ```
> Reduce verbosity with "using enum"
> ```

Is this the right setting? I don't see anything with that exact wording:
https://sonarcloud.io/organizations/piscsi/rules?open=cpp%3AS6177&rule_key=cpp%3AS6177

I've also added you as an owner for the SonarCloud project, so you should be able to make additional changes if needed.

**Comment by akuker** [comment]
Invitation sent to @dialtr to become a collaborator. Let me know if you have any issues!

**Comment by uweseimet** [comment]
@akuker I think this is the right setting. Sometimes I am also struggling with the exact meaning/wording of the settings. Let's just give it a try, we will know soon whether it is correct.

**Pull request merged**
