### PR TITLE
Freeze Python dependencies with pip freeze -l

### PR DESCRIPTION
**Pull request by rdmark**
Use `pip freeze -l` to programmatically capture the python dependency map for the python packages.

### CODE REVIEW

**Review by uweseimet — APPROVED** [review]
I trust that you have chosen the versions well ;-)

**Comment by uweseimet** [comment]
@rdmark You have commented on changes after approval very recently, haven't you? ;-)

**Comment by rdmark** [comment]
@uweseimet Thanks for reviewing. These versions are automatically calculated by `pip freeze` using the PyPI dependency tree. They are the same that pip will fetch and install presently, but freezing them protects against future changes to the state of PyPI.

I pushed a change just now with a note on this in the README, as well as the frozen dependencies for the `common` package (which I had overlooked before.)

**Comment by rdmark** [comment]
> You have commented on changes after approval very recently, haven't you? ;-)

@uweseimet Haha, I don't think that was me! I have full confidence in all project members to be responsible with their post-approval commits. ;)

**Pull request merged**
