### PR TITLE
easyinstall: Add ca-certificates to list of packages to install with apt

### PR DESCRIPTION
**Pull request by rdmark**
This may resolve intermittent errors when fetching files from github.com with wget, when running jobs on github runners

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark Why did dhcpcd have to be removed? The daynaport setup instructions refer to dhcpcd, and it is not installed implicitly on bookworm.

**Comment by rdmark** [comment]
@uweseimet If you look at the failed run for the first commit here, we were getting this error:

```
E: Package 'dhcpcd' has no installation candidate
```

I removed it to test that adding `ca-certificates` had the intended effect.

**Comment by uweseimet** [comment]
@rdmark But on bullseye is it still installed. I have to admit I am confused why dhcpdcd would be related to a certificate issue with github.

**Comment by uweseimet** [comment]
@rdmark OK, so adding the certificates is the resolution?

**Comment by uweseimet** [comment]
@rdmark In case that explicitly installing dhcpcd breaks something, any idea why it works why implicitly installing it? At least I think that's what we found: On bullseye it is installed implicity, at least /etc/dhcpcd.conf is there without explicitly installing dhcpcd. On bookworm /etc/dhcpcd.conf was missing.
NOT explicitly installing dhcpcd would not really change something for the release, as long as the bridge setup does not work with bookworm anyway.

**Comment by rdmark** [comment]
It seems `dhcpcd` simply isn't a valid standard package on Ubuntu 22.04.3 (the OS of the runner), but it definitely exists in Debian Bookworm repos.

**Comment by uweseimet** [comment]
@rdmark I see. Correct me if I am wrong: The problem has to do with the runners using Ubuntu and not Raspberry Pi OS.

**Comment by rdmark** [comment]
Agreed with your conclusion. Let's remove the dhcpcd package for this release, and revisit the bridge situation after the release.

And yes, adding the certificates package seems to have solved the issue with wget... I guess Github is actively tweaking their Ubuntu runner image and recently removed the ca-certificates package (deliberately or by mistake...?)

**Comment by uweseimet** [comment]
@rdmark I recommend reverting the change that prevented from wget to ignore certificates, though. At least if this change is not required.

**Comment by rdmark** [comment]
> @rdmark I see. Correct me if I am wrong: The problem has to do with the runners using Ubuntu and not Raspberry Pi OS.

You could put it that way, yes.

**Comment by rdmark** [comment]
> @rdmark I recommend reverting the change that prevented from wget to ignore certificates, though. At least if this change is not required.

Yes, I already discarded that PR without any action.

**Pull request merged**
