### PR TITLE
German translation update

### PR DESCRIPTION
**Pull request by cvictor**
Please remember that I still need a GIT nanny. Thorough review recommended. ;-)

### CODE REVIEW

**Review by rdmark — APPROVED** [review]
LGTM.

**Comment by rdmark** [comment]
@cvictor One suggestion for the next time: It's cleaner if you create a new branch with a different name each time you submit a new PR. I already had a `cvictor_german_translation` branch checked out locally from a few months ago and git got confused.

**Comment by cvictor** [comment]
Will use a unique name from now on. What would you suggest - append a date?

**Comment by rdmark** [comment]
Yes. I usually do year and month for simplicity, ex "2302"

**Pull request merged**
