### PR TITLE
Issues 1179 and 1182

### PR DESCRIPTION
**Pull request by uweseimet**
Besides resolving https://github.com/PiSCSI/piscsi/issues/1179 and https://github.com/PiSCSI/piscsi/issues/1182 this PR also resolves several SonarQube issues and decouples several classes, which also simplifies the unit test setup. The complete non-legacy code (more or less everything not in hal/ and not related to cfilesystem) was reviewed and cleaned up, resulting in more concise and less code than before.

@akuker Please disable this warning in SonarCloud:
```
Reduce verbosity with "using enum"
```
 We cannot address this issue because the bullseye compiler does not support "using enum".

### CODE REVIEW

**Comment by uweseimet** [comment]
@akuker Any idea when the buster release (planned for last weekend) will be available? Besides this PR the resolutions for other tickets (#807, #1214, #1219) are piling up and block working on other open issues.

**Comment by akuker** [comment]
> @akuker Once again I am disappointed about the lack of transparency. The final buster release was postponed without any further information. 
Its not like there is a team of 20 people that have been re-directed to a different priority without communication. We're all volunteers. We needed to get the translations in line before cutting the release, and the folks who typically do the translations haven't been available. I've hired some native speakers on fiverr to review the changes to help move the process along. These have been discussed in the discord dev channel.

I apologize for the perceived lack of transparency.

> My last question about the release has not been commented on even though several branches are ready for PRs. Numerous users have been waiting for ages on the feedback promised in their tickets. It's likely that some of them have already lost interest in the project.

Sorry to hear this. My original goal when I got started with this project was as an enthusiast to help make the original RaSCSI project more accessible outside the X68000 community. It appears I have become the bottleneck in the project successfully moving forward. I'll try to push through the existing PRs that are open and cut a release as soon as possible. Probably this weekend. After that, I'm going to be re-evaluating my role in this project.

PiSCSI has an amazing community built around it, and I'm excited to see how it will continue to grow. I hope to stay involved, but its not working to have me as the maintainer/bottleneck on progress.

**Comment by uweseimet** [comment]
@akuker Somehow I doubt that somebody else who is willing to maintain the project, but I hope that I am wrong. IMO what's currently not working well is that on the one hand you often mention that you have hardly any time for the project, but on the other hand besides maintaining releases you also announced several features that you wanted to work on (e.g. Banana Pi, SASI). With not enough time for everything (stewardship and implementation) I would like to encourage you to make the project stewardship the priority.
If there were more reviewers things would become easier, that's why I created #1242.

**Comment by uweseimet** [comment]
Successfully tested on a Pi 4 with the official 64 bit bookworm distribution.

**Comment by akuker** [comment]
> @akuker Somehow I doubt that somebody else would be willing to maintain the project, but I hope that I am wrong. 

I hope so as well. For my own well being, I need to step back. 

> With not enough time for everything (stewardship and implementation) I would like to encourage you to make the project stewardship the priority. If there were more reviewers things would become easier, that's why I created #1242 some days ago.

I hope #1242 helps recruit additional reviewers / volunteers. I need to step back. 

The vast majority of the changes didn't actually **DO** anything. Changes like #1182 may align with your vision for the project, and I hope you're able to continue towards that vision.

I looked at every file and am going to approve. I don't understand why most of the changes were necessary, but they look benign. I guess the code is "better" now.

**Review by akuker — APPROVED** [review]

**Comment by uweseimet** [comment]
@akuker  Thank you, just merged it. Not sure what you say the changes do not DO anything. This ticket was not about new features, but about refactoring in order to improve code qualitiy and making use of C++-20 in particular and more odern C++ features in general. This is not about my vision, but about best practices, which are explained in numerous books and, for instance, in the cppcon workshop videos, and about reducing SonarQube issues.

**Pull request merged**
