### PR TITLE
Bump dropzone library to v6.0.0-beta2

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Review by nucleogenic — APPROVED** [review]
@rdmark Seems like there's a later version available, beta2?

Neither of these beta versions, or v5.x have had a release in ~2 years, btw.

**Comment by rdmark** [comment]
Nice catch! Interestingly, beta2 isn't mentioned in their docs. But it is available on the CDNs. Looking at the [diff](https://github.com/dropzone/dropzone/compare/v6.0.0-beta.1...v6.0.0-beta.2) they added code for running on AWS S3, and a major refactoring of their unit tests. But that's about it. I'm leaning towards staying on beta1...

**Comment by rdmark** [comment]
Hm I finally got my docker environment working fully and found out that our code doesn't work with 6.0.0-beta*. Discarding this.

**Comment by rdmark** [comment]
Filed a bug upstream https://github.com/dropzone/dropzone/issues/2268

The project seems to be in flux, indeed. The original author hasn't been active since January, and there's talk about forking.

Closing until the upstream project has stabilized.

**Comment by rdmark** [comment]
I got help over at the Dropzone project. The trick was to call the `Dropzone.discover()` method.

**Comment by rdmark** [comment]
Beta 2 seems to be working fine, testing on my RPi3. Merging.

**Pull request merged**
