### PR TITLE
Fix output formatting for LUNs > 9 (#1254)

### PR DESCRIPTION
**Pull request by uweseimet**
Before:
```
+----+-----+------+-------------------------------------
| ID | LUN | TYPE | IMAGE FILE
+----+-----+------+-------------------------------------
|  1 |   0 | SCLP | SCSI Printer
|  1 |   31 | SCHS | Host Services
```
After:
```
+----+-----+------+-------------------------------------
| ID | LUN | TYPE | IMAGE FILE
+----+-----+------+-------------------------------------
|  1 |   0 | SCLP | SCSI Printer
|  1 |  31 | SCHS | Host Services
```

### CODE REVIEW

**Review by dialtr — APPROVED** [review]
LGTM

**Comment by uweseimet** [comment]
Thanks, Tom. Merging is still blocked, though. @akuker Looks as if there is still something that needs to be configured?

**Comment by rdmark** [comment]
@dialtr I made you a collaborator on this repo with Write privileges. With great power comes... ;)

**Comment by rdmark** [comment]
@uweseimet It seems like this is mergable now with Tom's approval.

**Pull request merged**
