### PR TITLE
Add initial IDE setup

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by rdmark** [comment]
So your argument for removing .vscode is that they have no reuse value to anyone else, and are strictly for the author's local environment? 

I don't know enough about VSCode configurations to say for sure, but it looks like they're attempting to set up a debugging environment. 

For those who are using VSCode, I can see two additional actions we want to take here:

1. Document the debug env setup as an example somewhere, either in a subdir here in the repo, or in wiki. 

2. Add .vscode to .gitignore so that VSCode users won't be inundated with noisy uncommitted files. 

Thoughts?

**Comment by uweseimet** [comment]
It's the same with all of these IDE/environment-specific files: They are specific to your personal setup. If you check them in, you destroy/overwrite the environment of somebody else. If somebody else modifies these files, the changes are forced upon your environment. Very annoying!
Regarding .gitignore, this is how this has to be done: Add any files/folders of this kind to your local .gitignore. This way git will ignore them, and everybody is happy because there are no conflicts.
Regarding debug setups: Those can also differ, depending on taste. Anybody who wants to debug knows how to set up her/his environment of choice and how to launch gdb. If somebody does know now how to do that she/he will not be able to debug anything anyway.

**Comment by uweseimet** [comment]
I just noticed that the .gitignore files checked in contain several items that may not belong there. Also items added by me, e.g. ".settings", ".cproject".
When looking at cpp/.gitignore, "generated" is a good example of something that belongs into this file, because this folder is created automatically when building piscsi. This means that each developer has to prevent this folder from being checked in, and this is not related to the IDE you use or your personal preferences.

**Comment by rdmark** [comment]
I had to read up on how to do local machine only .gitignore rules. What I learned is that the git manual recommends using .git/info/exclude

https://git-scm.com/docs/gitignore#_description

I agree that this is better than trying to anticipate every single IDE behavior.

**Review by rdmark — APPROVED** [review]

**Comment by uweseimet** [comment]
There is yet one more argument not to have IDE configurations checked in: Their format depends on the IDE version.
All in all, that's why IDE usually offer explicit export functionality for certain settings. This is also what I used for the Eclipse formatter configuration, which is exported as XML.

**Pull request merged**
