### PR TITLE
Config Nginx to serve Webmin via /webmin path

### PR DESCRIPTION
**Pull request by benjamink**
Configure Webmin to be served via '/webmin' URL path in Nginx along with the PiSCSI web UI.

- Makes the Webmin more consistent with existing PiSCSI web UI interface via a single URL 
- Removes the need to access Webmin via a custom part

>**_NOTE:_** It may be possible to more dynamically include the `location` configuration for nginx but I figured adding it statically wouldn't hurt anything either regardless of whether Webmin is installed or not.  If a more elegant solution is desired I can come up with something else.

### CODE REVIEW

**Comment by benjamink** [comment]
Relates to #1351

**Review by rdmark — APPROVED** [review]
This must mean that you're finding Webmin mildly useful? ;)

**Comment by benjamink** [comment]
@rdmark I was thinking about ways to incorporate system upgrades into the PiSCSI web UI but then I thought that can just be done via Webmin if someone really wants a UI to do it instead of the CLI.  I just thought it'd be convenient to have an easy path to Webmin for more novice users & thought it might make the experience more polished.

I've noted that a lot of people using PiSCSI don't know how to use the Linux CLI or know much about Linux in general so having Webmin would greatly simplify their lives.

**Comment by benjamink** [comment]
Merged in changes done in #1360 to this PR & closed the other one since they're dependent on each other.  This also tweaks the existing links to look a little better: 

image

**Comment by rdmark** [comment]
> @rdmark I was thinking about ways to incorporate system upgrades into the PiSCSI web UI but then I thought that can just be done via Webmin if someone really wants a UI to do it instead of the CLI. I just thought it'd be convenient to have an easy path to Webmin for more novice users & thought it might make the experience more polished.
> 
> I've noted that a lot of people using PiSCSI don't know how to use the Linux CLI or know much about Linux in general so having Webmin would greatly simplify their lives.

If you think Webmin has a broader use for non technical users, perhaps consider adding an entry point that’s not dependent on Samba or Netatalk being installed? E.g. somewhere on the Settings page.

**Comment by benjamink** [comment]
> If you think Webmin has a broader use for non technical users, perhaps consider adding an entry point that’s not dependent on Samba or Netatalk being installed? E.g. somewhere on the Settings page.

That was actually my original idea but I saw the links were already there so just customized them but I think I agree.  I reworked it again & put Webmin into it's own line item (only shows if its enabled/installed).  I think I like this better: 

image

**Comment by rdmark** [comment]
> > If you think Webmin has a broader use for non technical users, perhaps consider adding an entry point that’s not dependent on Samba or Netatalk being installed? E.g. somewhere on the Settings page.
> 
> That was actually my original idea but I saw the links were already there so just customized them but I think I agree. I reworked it again & put Webmin into it's own line item (only shows if its enabled/installed). I think I like this better:
> 
> image

I like it! Can we have both, though?

the original reason I chose to have deep links to either the Netatalk or the samba module, was because it bypasses the Webmin left rail menu and gives you a full screen view of either module. 

When in full screen mode, the overall Webmin web app runs faster on low powered devices such as a Zero, and refreshing the page refreshes the actual module sub page. When the left rail is loaded, refreshing the page takes you out of the module and drops you back to the dynamic Linux system dashboard which is veeeery heavy and runs like molasses on a Zero (or even a RPi 3). 

I’m open to suggestions however!

**Comment by benjamink** [comment]
Sure thing!  I was actually wondering if that’d be the response.  I’ll add them back in & keep the new standalone line item too.

**Comment by benjamink** [comment]
Re-added the per-service direct Webmin links: 

image


@rdmark do we want to install the `vsftpd` Webmin module (as a separate issue if we do it)?  It looks like it's a couple years old but maybe it's still worth having to round out Webmin support for all of the sharing services? https://www.webmin.com/cgi-bin/search_third.cgi?modules=1

image

**Comment by rdmark** [comment]
Ooh nice find. I didn’t consider vsftpd … because there isn’t a lot to configure? :)

If you think the module looks safe and solid, it would be nice to have for the symmetry, if nothing else!

**Comment by benjamink** [comment]
@rdmark new issue created for the vsftpd module install.  Anything remaining on this PR or should I merge it?

**Comment by uweseimet** [comment]
@benjamink Can you please make your merge comments more informative?
```
Merge pull request #1354 from benjamink/webmin-via-url-path
```
for instance does not say anything about what was changed. Usually the comments are very similar to the topic of the respective ticket.

**Comment by benjamink** [comment]
@uweseimet Oh, sorry about that.  I'll definitely craft my comments more carefully.  I just merged with the default comments (what I'm used to doing at work).

**Comment by uweseimet** [comment]
@benjamink I think the default comment is a list of commit messages, with the latest at the top. Usually I edit this comment, because I commit often, and many commit messages are useless when you later consult the log. Tpyically I have this in the suggest PR message:
```
* Fix SonarQube issue
* Fix another SonarQube issue
* Add unit test
* Add another unit test
* Meaningful comment describing the actual change
```
In such a case I remove all comments excpt the last one, or at least I merge identical/similar comments into one, as a summary.
This way I triy to remove the noise and keep the logs smaller and readable.

**Comment by benjamink** [comment]
@uweseimet At work I always set the default message for PR merge commits to be the title of the PR which automatically does what you're talking about (assuming the PR is titled well).  Any reason not to set this on this repo? 

Pasted_Image_11_17_23__6_27_AM

**Comment by benjamink** [comment]
Like this: 

image

**Comment by uweseimet** [comment]
@benjamink I guess I would be fine with this. What do the others think?

**Comment by rdmark** [comment]
For squash merging I suggest "request title and commit details" since the PR description isn't always kept up to date, but the commits always tell the truth, so to speak. When the commit log is messy, I usually go in and rewrite the squash commit message and remove noise from the list of commits (reverts, bug fixes to previous commits in the PR, etc.)

If you agree we can make this the official policy and update the README.

**Pull request merged**
