### PR TITLE
Update Spanish, French and Chinese translations

### PR DESCRIPTION
**Pull request by akuker**
Spanish and Chinese updates were done by Microsoft machine learning translation tools (via PoEdit Pro)
French translations were updated by [simonvictorm](https://www.fiverr.com/simonvictorm?source=order_page_user_message_link)

### CODE REVIEW

**Comment by rdmark** [comment]
The `test_settings.py::test_change_language` web test fails now because the French string for changing language changed:

```
"Langue de l’interface web changée en %(locale)s"
```

Do you mind updating the test? :)

**Comment by rdmark** [comment]
This might be intentional, but the French and Chinese translations aren't 100%.

```
Translation stats:
./src/translations/zh/LC_MESSAGES/messages.po
243 translated messages, 2 fuzzy translations, 11 untranslated messages.
./src/translations/fr/LC_MESSAGES/messages.po
255 translated messages, 1 untranslated message.
./src/translations/sv/LC_MESSAGES/messages.po
256 translated messages.
./src/translations/es/LC_MESSAGES/messages.po
256 translated messages.
./src/translations/de/LC_MESSAGES/messages.po
256 translated messages.
```

**Comment by akuker** [comment]
> Do you mind updating the test? :) ("pour" -> "en")

One step ahead of you! done :)

**Review by rdmark — APPROVED** [review]
The updated translations look good when compiled! Great job!

**Pull request merged**
