### PR TITLE
Run workflow jobs upon pushes to specific paths

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Review by uweseimet — APPROVED** [review]

**Comment by rdmark** [comment]
@uweseimet It seems like right now, a subsequent push with changed C++ code triggers C++ unit tests & sonar analysis. This is not what you saw in your PR?

Interestingly, it also triggers duplicate "Build ARM binaries"...

**Comment by uweseimet** [comment]
@rdmark You can see from the last commits in the issues_1263_1278_1283 branch what's currently happening in my case. The workflow in this branch is identical with the previous develop branch workflow, i.e. the one before the changes you have just applied for testing. At least if I am not missing something.

**Comment by rdmark** [comment]
Ah I see the difference. It's a work branch that you pushed to remote, but not yet created a PR for...

Just as a suggestion: If you create a PR in Draft state, I think it will work as you want it to. How about using PR Drafts as part of your workflow at the point when you want to start getting feedback on your code (from Sonar, or humans)?

**Comment by uweseimet** [comment]
@rdmark Please see my previous comment on the draft PRs: You get emails (also the reviewers I think) whenever you commit to a branch that has a draft PR and the analysis has run. I don't want to get tons of emails. Sometimes I discard a branch and do not create a PR at all. I would not want to create dummy PRs just to get a code analysis. I want to create a (draft) PR when I am sure that my changes are worth to be merged, and not before. And I would like to have an analysis for my current branch code. Without it you miss subtle bugs that the analysis would have revealed, and you start debugging without need.

Can't we just go back to how things were before you started to change the workflow?

**Comment by uweseimet** [comment]
@rdmark By the way, didn't you point out that you can trigger an explicit code analysis somehow? I have not found any means to do that, e.g. for the issues_1263_1278_1283 branch.

**Comment by rdmark** [comment]
Alright, I will put up a new PR to get us back to the previous behavior.

If you go to the Actions page and open the last job for your branch, there's a button to the top right for rerunning jobs.

**Comment by uweseimet** [comment]
@rdmark You can only re-run jobs that have already run. If on a branch a code analysis has never run, you cannot re-run it.

**Comment by uweseimet** [comment]
@rdmark Please tell me when the old workflow has been restored. I'm starting to lose track ;-).

**Comment by rdmark** [comment]
I think it should be back to the previous behavior now, but let me run a few more tests before saying for sure...

**Comment by uweseimet** [comment]
@rdmark OK. As far as I can tell it does not yet work. The workflow files still differ from how they were in the past, which might be expected because there were probably also other changes.

**Comment by rdmark** [comment]
Yes I made modifications to enable Sonar scanning of Python code when Python code changes. We can't go back to exactly the same configuration.

**Pull request merged**
