### PR TITLE
Improve performance when reading sectors

### PR DESCRIPTION
**Pull request by uweseimet**
This addresses item 1. in #1343.

### CODE REVIEW

**Comment by uweseimet** [comment]
Just thought that I should also test this on a Pi Zero, not just on a Pi 4. On the Zero optimization 2. in #1343 may (also) be interesting, even though it is not useful for the Pi 4. Making this PR to a draft until I have results on a Pi Zero.

**Comment by uweseimet** [comment]
On the Pi Zero there is also a slight improvement, and it definitely did not get slower.

**Review by rdmark — APPROVED** [review]
So about 1% increased read throughput on either RPi model ?

**Comment by uweseimet** [comment]
> So about 1% increased read throughput on either RPi model ?

On the Pi Zero you do not really see a difference. On the Pi 4 it is about 1%. Not much, but anyway: More speed because of less code ;-).

**Pull request merged**
