### PR TITLE
German language update

### PR DESCRIPTION
**Pull request by cvictor**

### CODE REVIEW

**Review by akuker — APPROVED** [review]

**Comment by rdmark** [comment]
@cvictor my apologies, there was code merged a moment ago that adds two translatable strings. Just FYI if you want to also translate those.

**Comment by cvictor** [comment]
For german it seems to be just one additional string (file server, shared directory).

Please double check if this pull request is valid since I had to re-pull my own branch and I'm not 100% sure I haven't f'ed up.

**Comment by rdmark** [comment]
@cvictor The commit log got a bit messy after you merged develop. Ideally you would squash the commits and force push. But it's no big deal this time since github allows us to squash when merging.

Also I think I mentioned this the last time, but please create a new branch with a unique name each time. Git gets confused when you already have a different branch locally with that name. Again, no big deal since I can manually delete the `cvictor_german_translation` branch that I have locally. But it's a good practice to keep in mind.

Apart from the formalities, I think the translation file looks good. No error when using it in the web app.

Just one parenthesis too many in this string:
```
Du musst (aufgrund unterbrochener Übertragung oder verlassen der Seite) teilweise hochgeladene Dateien selbst aufräumen.
```

**Comment by cvictor** [comment]
@rdmark I'll put that on the "how to not make rdmarks life harder" list.

**Pull request merged**
