### PR TITLE
Web UI: Create a system admin page and move options there

### PR DESCRIPTION
**Pull request by rdmark**
Create a new admin page with an entry point in the header

Remove system operations, system name, language, logging, log level from the index page. Remove theme, file sharing, macproxy from the footer. Put them all on the new admin page.

Added svg icons from the same set as the MIT licensed ones we're using now: https://github.com/feathericons/feather/tree/main/icons

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark I just noticed that for my current branches SonarCloud reports a new Python issue, which most likely appeared in my branch after merging the current develop branch into mine. https://sonarcloud.io/project/branches_list?id=akuker_PISCSI does not list any SonarCloud analysis for your current PRs, but only for other branches. Any idea why the SonarCloud data for your PRs seem to be missing?

**Comment by akuker** [comment]
I believe the security token expired for sonarcloud. (The last token was created in Sept 2023, so makes sense it would expire after a year) Working to fix it now....

**Comment by rdmark** [comment]
@uweseimet I rebased and force pushed this branch after @akuker 's bump to sonar v5 and the analysis ran and found two issues with the html code: 

https://sonarcloud.io/summary/new_code?id=akuker_PISCSI&branch=rdmark-issue-1218

However it didn't report Python code quality issues so I'm not sure what happened in your branch?

**Comment by uweseimet** [comment]
@rdmark You can see the issue (code smell) on https://sonarcloud.io/summary/new_code?id=akuker-PISCSI&branch=issue_1182. The affected file has not been changed by me, but it is reported in my branch.

**Comment by rdmark** [comment]
@uweseimet In this Sonar report I can see the one code smell for `python/web/src/templates/base.html` ... a fix for this has been force pushed to this PR.

**Comment by rdmark** [comment]
With some tweaks done to the CI workflow elsewhere, we now finally get Python static analysis reports for Python PRs.

**Comment by rdmark** [comment]
@uweseimet This is the final code change for the clients that I want to make before the next release. After that I will rebase the translation updates PR and refresh it with machine translated strings.

Hopefully @nucleogenic will have a chance to look at it soon!

**Comment by rdmark** [comment]
This PR has been tested and pending for a month now. I'm going to bypass the branch protection and merge this.

**Pull request merged**
