### PR TITLE
Clarify docs and error strings for scsimon

### PR DESCRIPTION
**Pull request by rdmark**
- Pull in some docs from wiki to man page
- Clarify in error message that other processes can't use the gpio bus

### CODE REVIEW

**Review by uweseimet — CHANGES_REQUESTED** [review]
I don't think the error message should be changed. The new message is less precise and thus less helpful for the user. It does not give any hint which process may be the offending one, and the ordinary user would also not know what a GPIO bus is.

**Comment by rdmark** [comment]
@uweseimet I pushed a new revision now with a tweaked error message. What do you think?
The reason I want to change the error message, is that the current phrasing has proven ambiguous to at least one user.
The "Is PiSCSI or RaSCSI already running?" message isn't actionable, since it doesn't explicitly state which one is the correct state: running or not running.

**Review by akuker — APPROVED** [review]
Looks great! Thank you!

**Comment by uweseimet** [comment]
@rdmark I'm fine with the text now, but if just one user wants a change this should not automatically mean that something is going to be changed. All other users may have been fine with how it was before. What happens if after such a change another user (or two other users) want this change to be reverted? Do we revert it then? :) You cannot please everybody.

**Review by uweseimet — APPROVED** [review]

**Pull request merged**
